### PR TITLE
fix: ensure backend connector remains available until last serialization completes

### LINKED ISSUE #236: Postpone backend connector shutdown if serialization is pending
When the application is shut down, usually also backend connector internal components that communicate with the remote storage get closed by Spring.
This could lead to a situation where pending serialization on shutdown cannot be completed because the connection with the backend has already been dropped.
The Kit should notify backend connectors about pending serialization and allow them to postpone their close until the process is completed.

Options could be adding a method in `BackendConnector` that takes a `Runnable` or a `CompletableFuture` that can be hooked into the backend lifecycle APIs

For example, Hazelcast has `HazelcastInstance.getLifecycleService().addLifecycleListener(...)` that is notified about `SHUTTING_DOWN` event, but this should be carefully investigated because Javadoc says blocking calls are not allowed

### PR DESCRIPTION
**Pull request by mcollovati**
Disables Hazelcast shutdown hook to prevent premature HazelcastInstance termination before SessionSerializer completes pending serializations.

- Disable Hazelcast shutdown hook in KubernetesKitConfiguration
- Add a warning log when a shutdown hook is enabled in HazelcastConnector
- Add optional slow serialization simulator bean for testing

This ensures the session state is fully propagated to the cluster before the backend connector is torn down during application shutdown.

Fixes #236

### CODE REVIEW

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java [hunk 1]
```diff
@@ -303,6 +303,9 @@ public HazelcastInstance hazelcastInstance() {
             final var config = new Config();
 
             configure(config);
+            // Make sure Hazelcast shutdown hook is disabled so that the instance
+            // will be stopped after SessionSerializer saved the latest pending state
+            config.setProperty("hazelcast.shutdownhook.enabled", "false");
```
Comment (heruan) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java]: If we disable the shutdown hook here, when the `HazelcastInstance` will be closed? Should we add `@Bean(destroyMethod = "shutdown")` to let Spring handle it?

Comment (mcollovati) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java]: We don't need to set the destroyMethod attribute. Spring by convention invokes `shutdown` for bean if existing
