### PR TITLE
fix: dont attempt pessimistic on NotSerializableException

### LINKED ISSUE #49: Stop serialization when optimistic attempt fails with NotSerializableException
Currently, when the optimistic attempt fails with NotSerializableException, the error is caught, and the process proceeds with the pessimistic attempt, that however will fail with the exactly same error.

In case of NotSerializableException the process should be stopped immediately.

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

When optimistic serialization fails with NotSerializableException it does not make sense to attemp pessimistic approach, since it will fail with the same error.

Fixes #49

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java [hunk 1]
```diff
@@ -242,18 +243,26 @@ private void handleSessionSerialization(String sessionId,
                     return;
                 }
             }
+        } catch (NotSerializableException e) {
+            getLogger().trace(
+                    "Optimistic serialization of session {} with distributed key {} failed,"
+                            + " some attribute is not serializable. Giving up immediately since the error is not recoverable",
+                    sessionId, clusterKey, e);
```
Comment (heruan) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java:250]: Should this be at `warn` or `error` level to be more visible?

Comment (mcollovati) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java:250]: Good catch

Comment (mcollovati) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java]: done

**Review by heruan — APPROVED** [review]
