### PR TITLE
fix: improve debug tool performance

### LINKED ISSUE #147: session serialization debug can get very slow
Hunting down a session serde problem, it was painful having to wait almost a minute between clicks for the application to settle down and stop showing the blue scrollbar. Is there anything that can be done to make this useful again? 

Also, from the output you see that one sessions serde times out at 30000ms but all the others complete succesfully at 40 seconds or more. Does that indicate a bug perhaps ? 

```
2024-10-25T16:05:28.526+02:00  INFO  4121996 --- [dev_heymajo] [io-8080-exec-10] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 50007 ms with outcomes: [SUCCESS]
2024-10-25T16:06:15.823+02:00  INFO  4121996 --- [dev_heymajo] [io-8080-exec-10] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 47137 ms with outcomes: [SUCCESS]
2024-10-25T16:07:03.298+02:00  INFO  4121996 --- [dev_heymajo] [io-8080-exec-10] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 47319 ms with outcomes: [SUCCESS]
2024-10-25T16:07:47.688+02:00  INFO  4121996 --- [dev_heymajo] [io-8080-exec-10] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 44152 ms with outcomes: [SUCCESS]
2024-10-25T16:08:32.565+02:00  INFO  4121996 --- [dev_heymajo] [io-8080-exec-10] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 44724 ms with outcomes: [SUCCESS]
2024-10-25T16:09:17.728+02:00  INFO  4121996 --- [dev_heymajo] [io-8080-exec-10] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 44943 ms with outcomes: [SUCCESS]
2024-10-25T16:10:07.428+02:00  INFO  4121996 --- [dev_heymajo] [io-8080-exec-10] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 49528 ms with outcomes: [SUCCESS]
2024-10-25T16:10:37.299+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-4] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 42392 ms with outcomes: [SUCCESS]
2024-10-25T16:11:07.454+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-2] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 30000 ms with outcomes: [SERIALIZATION_TIMEOUT]
2024-10-25T16:11:16.959+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-4] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 37752 ms with outcomes: [SUCCESS]
2024-10-25T16:12:21.044+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-9] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 47086 ms with outcomes: [SUCCESS]
2024-10-25T16:13:09.242+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-9] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 48050 ms with outcomes: [SUCCESS]
2024-10-25T16:13:57.514+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-9] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 47459 ms with outcomes: [SUCCESS]
2024-10-25T16:14:46.272+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-9] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 48607 ms with outcomes: [SUCCESS]
2024-10-25T16:15:35.215+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-9] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 48795 ms with outcomes: [SUCCESS]
2024-10-25T16:16:25.924+02:00  INFO  4121996 --- [dev_heymajo] [nio-8080-exec-9] s.s.s.d.SerializationDebugRequestHandler : Session serialization attempt finished in 50118 ms with outcomes: [SUCCESS]

```

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

Prevents concurrent request to hijack an ongoing serialization job causing timeouts.

Fixes #147

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java [hunk 1]
```diff
@@ -272,7 +272,7 @@ private void queueSerialization(String sessionId,
         // sense to retry the operation instantly.
         CompletableFuture.runAsync(
                 () -> backendConnector.markSerializationStarted(clusterKey),
-                executorService).whenComplete((unused, error) -> {
+                executorService).handle((unused, error) -> {
                     if (error != null) {
                         pending.remove(sessionId);
```
Comment (MatthewVaadin) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java:277]: If the `sessionId` is removed in the `whenComplete()` stage, does it need to done here too?

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java [hunk 2]
```diff
@@ -79,30 +85,54 @@ class Job {
...
-            completed = serializationLatch.await(timeout,
+            completed = serializationStartedLatch.await(timeout,
                     TimeUnit.MILLISECONDS);
             if (!completed) {
                 timeout();
                 logger.error(
-                        "Session serialization timed out because did not complete in {} ms. "
-                                + "Increase the serialization timeout (in milliseconds) by the "
-                                + "'vaadin.serialization.timeout' application or system property.",
+                        "Session serialization timed out because did not started in {} ms, "
```
Comment (MatthewVaadin) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java:95]:
```suggestion
                        "Session serialization timed out because it did not start in {} ms, "
```

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java [hunk 3]
```diff
@@ -79,30 +85,54 @@ class Job {
...
             logger.error("Testing of session serialization failed", e);
         }
+        if (completed) {
+            try {
+                completed = serializationCompletedLatch.await(timeout,
+                        TimeUnit.MILLISECONDS);
+                if (!completed) {
+                    timeout();
+                    logger.error(
+                            "Session serialization timed out because did not complete in {} ms. "
```
Comment (MatthewVaadin) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java:110]:
```suggestion
                            "Session serialization timed out because it did not complete in {} ms. "
```

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java [hunk 4]
```diff
@@ -79,30 +85,54 @@ class Job {
...
+                                    + "Increase the serialization timeout (in milliseconds) by the "
```
Comment (MatthewVaadin) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java:111]:
```suggestion
                                    + "Increase the serialization timeout (in milliseconds) using the "
```

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java (hunk 1 above)
Comment (mcollovati) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java:277]: Good point. This line can be removed

Comment (mcollovati) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java]: done

**Comment by mcollovati** [comment]
Should most likely be back-ported to all maintained branches.

**Review by MatthewVaadin — APPROVED** [review]
Nice work finding this performance improvement!
