### PR TITLE
fix: run debug tool after Vaadin request is processed

### LINKED ISSUE #44: Run Session Serialization debug tool after Vaadin processes the request
Currently, the serialization debug tool runs as a RequestHandler, installed by a VaadinServiceInitListener and for this reason, it is executed before any other internal handler.
More specifically, it runs before the UIDL handler, so the outcomes of the tool are referred to the previous request, not the current.

The tool should instead run after Vaadin completes to process the request.

Some ideas for the implementation:
- Make the tool run in a servlet Filter in combination with a request handler that triggers the execution (e.g. request attribute)
- Try to replace the UIDL handler with an extension that runs the tool after the UIDL request is processed

### LINKED ISSUE #46: Report Debug Tool outcomes in the browser
Currently, the Debug Tool prints results on server log.
It would be useful to also have some sort of notification on the browser, to have an immediate feedback.

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

Debug Tool is now executed by an HTTP Filter at the end of the request. The Filter gets an executable command set by the RequestHandler as request attribute, only for UIDL requests.
If PUSH is enabled, a notification will visible on the browser in case of failures.

Fixes #44
Fixes #46

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by jouni** [comment]
Should we treat this as an official named tool? I see it's currently being referred to in both lower and uppercase in the docs ("debug tool" and "Debug Tool"). Or

**Comment by mcollovati** [comment]
> Should we treat this as an official named tool? I see it's currently being referred to in both lower and uppercase in the docs ("debug tool" and "Debug Tool").

We will use the lowercase form. I'll update the docs

File: kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SerializationDebugRequestHandlerTest.java [hunk 1]
```diff
@@ -58,15 +90,31 @@ void setUp() {
...
+                .thenReturn(toolRunner);
+        when(httpRequest.getSession(false)).thenReturn(httpSession);
+        when(httpRequest.isRequestedSessionIdValid()).thenReturn(true);
         resultHolder = new AtomicReference<>();
-        doAnswer(i -> resultHolder.compareAndSet(null, i.getArgument(1)))
-                .when(request)
-                .setAttribute(eq(
-                        SerializationDebugRequestHandler.SERIALIZATION_TEST_REQUEST_ATTRIBUTE_KEY),
-                        any());
+        /*
```
Comment (MatthewVaadin) [inline kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SerializationDebugRequestHandlerTest.java:113]: Remove commented out code.

**Review by MatthewVaadin — CHANGES_REQUESTED** [review]
There is no such word as "notificator". Can we rename the component to `SessionDebugNotifier`?

**Comment by mcollovati** [comment]
> There is no such word as "notificator". Can we rename the component to `SessionDebugNotifier`?

@MatthewVaadin we have also `VersionNotificator` for the cluster support. We should change that also, but perhaps in another PR

File: kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SerializationDebugRequestHandlerTest.java (hunk 1 above)
Comment (mcollovati) [reply kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SerializationDebugRequestHandlerTest.java]: done

**Review by MatthewVaadin — APPROVED** [review]
