### PR TITLE
fix: reject concurrent requests during deserialization

### LINKED ISSUE #234: SessionTrackerFilter: reject requests if deserialization is in progress
After a server change, the Kit must ensure that a single HTTP session is created for a given cluster key, to prevent multiple requests to make changes to the UIs on different sessions, causing an `Unexpected message` error.
This has been already addressed by #223, but the same issue may occur if concurrent requests are sent to different nodes of the same cluster. Usually, this happens when because of an incorrect configuration of sticky sessions in load balancers, but the Kit should anyway ensure that only one request per cluster key creates an HTTP session.

To achieve it, `SessionTrackerFilter` should track deserialization events by calling `BackendConnector` lifecycle methods introduced by #231.
In the specific, if `markDeserializationStarted` signals that a deserialization is already in progress, the filter should reject the incoming request by waiting for HTTP session deserialization completion and then returning a 307-redirect response, so that the client can retry the request again with an update session cookie.

### PR DESCRIPTION
**Pull request by mcollovati**
Fixes #234

### CODE REVIEW

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java [hunk 1]
```diff
@@ -231,6 +232,40 @@ public boolean isRunning() {
...
+     *            the distributed storage key associated with the session to be
+     *            created.
+     * @param request
+     *            the HttpServletRequest used to create the HTTP session.
+     * @return the newly created HTTP session, or {@code null} if the
+     *         deserialization process could not be started or an exception
+     *         occurred.
+     */
+    public HttpSession createHttpSession(String clusterKey,
+            HttpServletRequest request) {
```
Comment (heruan) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java]: Do we need this new method to be public?

Comment (mcollovati) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java]: Good point. I think we ca make it package protected
