### PR TITLE
fix: add ttl for peding session key

### LINKED ISSUE #189: pending session keys
We observed that in our session store (Redis), kubernetes-kit creates "pending-" keys but does not remove them. Following the logic in `SessionSerializer#queueSerialization`, the intent is that the pending key is deleted as soon as the actual session key is sent but there seem to be some edge cases where this does not happen. For example, if the `sendSession` call fails then `markSerializationComplete` does not get called. 

Here's an example list from one of the redis servers:

```
"pending-1e0b25c1-4210-4d8a-97d2-0f28501a7cdb"
"session-bdee2d6d-9b15-48f7-b5c4-3ee0fb03c4a1"
"pending-be5561e0-def8-460b-8a5e-3ba191de1973"
"session-ca1bfdc2-3fd4-418a-9a89-e2c1aabcc2a9"
"session-965769f8-47c0-4cad-9bd7-ac465c1b0a58"
"pending-7e70c1e5-e07a-4729-a228-d27d31369eb5"
"session-2b9b7874-a583-48cd-bb29-b7e501d53842"
"pending-493ef011-0a69-435a-92ab-bbe3fe191036"
"session-689dae45-eb5d-43ae-a4f5-96bacadb9e7f"
"pending-c73cff71-a4cb-4358-ac31-9d069b66979c"
"session-7571aa20-4106-47c8-a273-faab982c9ff8"
"session-0e74e9a4-0373-4988-bf5e-c752a0e8830d"
"pending-8b895070-043e-445c-872c-c838e0d2f877"
"session-6ed17754-70be-4fb7-957e-218e8a721871"
"pending-9b96b5c9-5339-4887-9b18-7b4ba63041e1"
"pending-f0b8f0ae-3d72-42c7-a325-cd49da1a44d4"
"session-0e299f07-3685-4f60-8985-0ad80ae3756c"
"session-270c7053-58f6-476d-9191-536e1881df0f"
"session-26452b59-2f9d-44df-8a7e-a5c895abec8c"
"pending-c65e06e3-2d18-4824-b375-58b1a6248b9d"
"session-227f5ee4-0d9a-41c0-bf7b-2237bcd4e185"
"pending-05435871-9123-49c9-be6a-6eafbb4e18da"
"pending-7a34dd41-380d-4b3e-8a1d-8f7d856825e3"
"session-7c86bc46-24e4-4052-92a6-7185576d2e7e"
"pending-800ba62a-3ca6-41ac-820a-fb881b88d741"
"session-c07e36ba-962b-439e-bf0a-cb194fe43b2f"
"session-b6c232c7-5d39-4f61-b364-347e97abd8a5"
"session-419291fc-187c-4f4d-ad9a-e7e8aa5cd298"
"session-0780fac5-cc0b-4938-b68e-ac557a02a0c6"
"pending-7b6134e9-5b3f-42e3-a08c-65625ba66e74"
```

I think it would be more prudent to create these "pending" keys with the same TTL logic as the actual session keys. That way, even in case of session serialization issues they don't linger around forever.

### PR DESCRIPTION
**Pull request by tamasmak**
The pending session keys should be removed if there is an error during the serialization. If some error happens during the pending session keys removal (like error while connecting to the backend caches or key deletion error), the TTL for the pending session keys will make sure that those are still removed.

- Marks the serialization failed and deletes/unlocks the pending sessions keys in the Redis/Hazelcast caches when the serialization fails with error before it could be marked as completed
- Adds TTL for the pending session keys when the serialization is marked as started in Redis and Hazelcast connectors. The TTL duration for the pending session keys is set to be the same as for the final session keys
- `RedisConnection` has some deprecated methods (`set()`, `del()`, etc.), those are replaced to be used with `RedisStringCommands.stringCommands()` `RedisKeyCommands.keyCommands()`

Closes #189

### CODE REVIEW

File: kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java [hunk 1]
```diff
@@ -380,14 +385,39 @@ void serialize_notSerializableException_notFallbackToPessimistic() {
...
+
+        vaadinSession.setLockTimestamps(10, 20);
+
+        serializer.serialize(httpSession);
+        await().atMost(100, MILLISECONDS).untilTrue(serializationStarted);
+        verify(connector).markSerializationStarted(clusterSID, timeToLive);
+
+        await().atMost(500, MILLISECONDS).untilTrue(serializationFailed);
+        assertThrows(RuntimeException.class,
+                () -> connector.sendSession(any()));
```
Comment (mcollovati) [inline kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java:417]: This assertion should be removed: `connector.sendSession(...)` should be called by the serializer, not by the test code.

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java [hunk 2]
```diff
@@ -313,6 +313,8 @@ private void queueSerialization(String sessionId, Duration timeToLive,
                 }).whenComplete((unused, error) -> {
                     pending.remove(sessionId);
                     if (error != null) {
+                        backendConnector.markSerializationFailed(clusterKey,
```
Comment (mcollovati) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java:316]: nit: `error` will most likely be a `CompletionException`. In this case, it would be nice to unwrap and forward the real cause to the connector.

Comment (mcollovati) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java:316]:
```suggestion
                        if (error instanceof CompletionException && error.getCause() != null) {
                            error = error.getCause();
                        }
                        backendConnector.markSerializationFailed(clusterKey,
```

File: kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java [hunk 3]
```diff
@@ -380,14 +385,39 @@ void serialize_notSerializableException_notFallbackToPessimistic() {
...
+        verify(connector).markSerializationFailed(eq(clusterSID), any());
```
Comment (mcollovati) [inline kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java:418]: If we unwrap `CompletionException` in `SessionSerializer` the we can verify that the exact exception is given to the connector


```suggestion
        verify(connector).markSerializationFailed(eq(clusterSID), same(throwable));
```

**Review by mcollovati — CHANGES_REQUESTED** [review]

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/BackendConnector.java [hunk 4]
```diff
@@ -9,14 +9,24 @@
...
 
     void deleteSession(String clusterKey);
 
+    /**
+     * @deprecated use {@link #markSerializationStarted(String, Duration)}
+     */
+    @Deprecated(since = "2.4", forRemoval = true)
     void markSerializationStarted(String clusterKey);
 
+    void markSerializationStarted(String clusterKey, Duration timeToLive);
```
Comment (mcollovati) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/BackendConnector.java:27]: To ensure backward compatibility, we can implement this as a default method, invoking the deprecated method internally.  A corresponding warning message in the log will prompt developers to migrate their code (e.g. `markSerializationStarted(String clusterKey) is deprecated and will be removed. Please implement the proper markSerializationStarted(String clusterKey, Duration timeToLive) method in ${getClass().getName()}`.

File: kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java (hunk 1 above)
Comment (tamasmak) [reply kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java]: Removed this assertion.

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java (hunk 2 above)
Comment (tamasmak) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java:321]: Added the suggested check to unwrap the `CompletionException`.

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/BackendConnector.java (hunk 4 above)
Comment (tamasmak) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/BackendConnector.java]: We've discussed that we won't add any deprecated method in this case. I'm closing this comment.
