### PR TITLE
fix: postpone push on server shutdown

### LINKED ISSUE #235: NotifyingPushConnection: send empty response message to the client during shutdown
When the server is shutting down, the Kit should prevent PUSH messages from being sent to the client so that it cannot send further requests that might change the VaadinSession.
Sending an empty message (`for(;;);[]`) instead of the proper UIDL response will cause the Flow client to stop sending any more requests while waiting for the acknowledgement of the previous request.

The missing response should be then re-sent on websocket reconnection. In the worst case, the client sync id will be behind the server-stored id and a clean client-side initiated resyncing should happen.

This situation probably only happens with full WEBSOCKET transport and/or high-frequency background thread push, so it could be hard to reproduce and test

### PR DESCRIPTION
**Pull request by mcollovati**
When the server is going down, ignore incoming PUSH requests to prevent changes from being applied to the UI. The change requests are anyway enqueued and serialized and are applied when the connection with the server is re-established.

Fixes #235

### CODE REVIEW

File: kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/NotifyingPushConnection.java [hunk 1]
```diff
@@ -71,6 +84,10 @@ private void notifyPushListeners(Consumer<PushSendListener> action) {
         }
     }
 
+    private Logger getLogger() {
+        return LoggerFactory.getLogger(getClass());
+    }
```
Comment (heruan) [inline kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/NotifyingPushConnection.java]: Can we initialize the logger as a static field instead?

Comment (mcollovati) [reply kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/NotifyingPushConnection.java]: done

**Review by heruan — APPROVED** [review]
